apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
  - configuration:
      apiVersion: pod-security.admission.config.k8s.io/v1
      defaults:
        audit: restricted
        audit-version: latest
        enforce: restricted
        enforce-version: latest
        warn: restricted
        warn-version: latest
      exemptions:
        namespaces:
          - ingress-nginx
          - kube-system
      kind: PodSecurityConfiguration
    name: PodSecurity
